name: CI/CD

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install node
        uses: actions/setup-node@v5
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Check style
        run: npx prettier --check .
